### ISSUE TITLE
not showing full size deepin 20.1

### ISSUE THREAD

**Issue by aksharlabs** [deepin-espanol/DDE-Dock-pugin-basic#1]
![Screen Capture_select-area_20210101131805](https://user-images.githubusercontent.com/74598801/103433445-497ef700-4c34-11eb-899f-1ed75c58b13b.png)

**Comment by N1coc4colA** [comment]
Thank you for this report! We found a fix for that. In a close commit, this issue will be fixed with success.
You'll be able to watch our random numbers again and again! :)

**Comment by N1coc4colA** [comment]
Bug fixed in commit bf86a812288e215e130f68743072f03a596bd4f5.
Now works perfectly. Thank you
